### ISSUE TITLE
Cleanup: Move grid code in link-utils to grid-utils

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#3097]
`grid-utils` was introduced in 1.9.  Feels like a natural home for some of the util methods in `link-utils`

**Comment by davidwatkins73** [comment]
Also fixing some issues reported by: [LGTM](https://lgtm.com/projects/g/khartec/waltz/)

**Comment by sjvs** [comment]
Hi @davidwatkins73! Glad to see that the LGTM.com alerts are of use :slightly_smiling_face:. I see you also have a significant amount of Java code; I'll try to enable analysis for that.

Have you considered enabling LGTM's automatic code review for pull requests? Here's an example of how that works for the AMPHTML project: https://github.com/ampproject/amphtml/pull/13060. It's very easy to set up: https://lgtm.com/projects/g/khartec/waltz/ci/

(Full disclosure: I'm part of the team that built LGTM.com)

**Comment by davidwatkins73** [comment]
Hi @sjvs , thanks for the note. I expect the Java code won't build as we use generate database code (via jOOQ) as part of our build.  We run liquibase to create the database (if needed) as part of the build.  This works on Travis (see [config file](https://github.com/khartec/waltz/blob/master/.travis.yml)) because we set a database server (mariadb) as a build dependency. 

The Javascript reporting has been useful and all of the issues looked like they needed remediation. We'll try setting up the automatic integration soon.

Thanks again,
Dave

**Comment by sjvs** [comment]
Indeed — I found that out the hard way :slightly_smiling_face: 

Is it possible to include the generated database code in the repository (rather than create a database and running SQL queries at build time)? Alternatively, would it be possible to include a sqlite variant? That'd work without having to start a database service.

**Comment by davidwatkins73** [comment]
I can imagine, Waltz isn't exactly a small project ;)

We've tried not to include generated code in the repository.  However we have been talking about (re)adding support for postgres and possibly looking to support one of the embedded db's for integration testing.  However I don't think this is imminent!

**Comment by davidwatkins73** [comment]
Have you considered adding support for a maven plugin (or similar).  Our stats could then be reported as a side-effect of the travis build...

**Comment by davidwatkins73** [comment]
FYI, setup the auto-integration.

**Comment by sjvs** [comment]
Great! 

Creating a Maven plugin is unfortunately not straightforward: it'd require our analysis to be packaged up in order to run on Travis build machines.

I've created a custom build configuration for analysing Java code in Waltz. The configuration patches the pom.xml to disable the build targets that require a running DBMS. Unfortunately this only leaves `waltz-common` and `waltz-model`; the other modules depend on `waltz-schema`.

I'll file a PR in a moment to store the LGTM analysis configuration in your repository so you can tweak LGTM's behaviour if/when your build process changes.
