### ISSUE TITLE
Measurable Category: error logged in console

### ISSUE THREAD

**Issue by rovats** [finos/waltz#4554]
```TypeError: Cannot read property 'kind'```

Suspect this is because of the people section on `measurable-category-list.html`, as `vm.categoryRef` is undefined until the server API call returns:

```javascript
serviceBroker
            .loadAppData(CORE_API.MeasurableCategoryStore.findAll)
            .then(r => {
                vm.categories = r.data;
                vm.category = _.find(vm.categories, { id: $stateParams.id });
                ***vm.categoryRef = toEntityRef(vm.category);***
                if (vm.category.editable) {
```

**Comment by davidwatkins73** [comment]
Can't recreate - don't think it's caused by the line identified as a placeholder ref is defined at the top of the file:  

```
vm.categoryRef = {
        id: categoryId,
        kind: "MEASURABLE_CATEGORY"
    };
```

however this wasn't added until the 2019-12-03 - so only a few days before this issue was raised - perhaps this fixed it.. ?

Will make a commit anyway as have improved the test data generator to include category involvements.
