### ISSUE TITLE
Waltz doesn't build from zip file.

### ISSUE THREAD

**Issue by strangetobefree** [finos/waltz#5086]
Just a small issue! if you download the latest version from zip - the build will fail at the last hurdle- something in the build is downloading from git so if this isn't configured then you can't build. This is only an issue if you can't install GIT of course, but might be worth fixing. 

the issue is with NPM in the Waltz-web build stage. NPM seems to have removed the logs but if you can't recreate let me know and I'll have a go.

**Comment by davidwatkins73** [comment]
Hi Stephen,
This will be because we include a build number in the gui which is taken from the latest git revision.  The client (at runtime) checks with the server to make sure it's on the latest version and if not forces a reload.  We use the to prevent client side caching introducing mismatches between the client and server.

I'll look to see if we can provide a fallback value if git is not present (and/or) the directory is not a git project.

A workaround _should_ be to simply do a `git init` (and possibly a `git commit -a`) to ensure there is a valid git repository available.

**Comment by strangetobefree** [comment]
yes that sounds right david - thought it would be something like that!

might be worth adding the fallback but as I said, it's not a major problem. I've included a GIT download in our build process here to get around the issue (and because it's easier) so our usage is unaffected.
