### ISSUE TITLE
13th January 2022 - Waltz Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#5813]
## Date
Thursday 13th January 2022 - 10am ET / 3pm UK
Occurs the second Thursday of every month 

## Additional Attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|
| Shane Morris | RBC | |
| Dave Watkins | Deutsche Bank | |
| Aaron Haines | NatWest | |
| Jessica Woodland-Scott | Deutsche Bank | |
| Stephen Sui | RBC | |
| Claudia Cabas | RBC | |
| Andrew Deri-Bowen | NearForm | |
| Alex Chung | NatWest | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Latest Waltz updates and releases
- [x] Review items from last meeting and prioritise for potential community participation - https://github.com/finos/waltz/issues/5787
- [x] https://github.com/finos/community/issues/152
- [x] AOB, Q&A & Adjourn (5mins)

## Meeting Minutes
- Please at the link below for meeting minutes ...
  - https://github.com/finos/waltz/issues/5813#issuecomment-1021146058

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m00a97bac66d1324e1ca89b9bb4eb37c6

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 2554 479 5248

**Github Repo:** https://github.com/finos/waltz/

**Project Microsite:** https://waltz.finos.org

**Comment by davidwatkins73** [comment]
# 1.39

Target release date: **25 Jan 2022**

## Highlights

### Survey Management / Action UI Overhaul

As the volumes of surveys have steadily increase we have noticed deficiencies in the UI which has made it difficult for users to see their 'queue' of both surveys to complete and those to approve.  

![image](https://user-images.githubusercontent.com/576829/149342077-9dee201c-610c-4cc8-aad1-48892808f571.png)
Split across [many issues](https://github.com/finos/waltz/issues?q=is%3Aissue+milestone%3A%22done+-+Current+%281.39%29%22+survey).

### Survey Copy function (WIP)

This will allow users to copy the responses from one survey into another survey (of the same type).  User will be able to select which questions/sections to copy and whether to overwrite existing responses.

#5818 


### Docker build

Release builds will create a docker image and publish it to the [GitHub / FINOS packages repo](https://github.com/orgs/finos/packages).

![image](https://user-images.githubusercontent.com/576829/149332022-47b45d55-51d0-4f85-8d28-7f863b9a3cae.png)
#5801 


### Self Service Report Grids

Allow users to create ad-hoc report grids.  Private grids can be shared to select users by there owners and administrators can promote the grid to be public, which gives access to all users.

![image](https://user-images.githubusercontent.com/576829/149330500-4edb46e1-2776-4b16-bed7-cee0d9f4417e.png)
#5682 


### Source and Target Flow Diagram Improvements

Continued making improvement to the new source and target diagram.  Users can now easily flip direction (inbound vs outbound) and filters work against entire hierarchies (rather than just the visible bit).  Much more contextual information is shown when various elements on the diagram are selected.

![image](https://user-images.githubusercontent.com/576829/149341397-bd95766d-5919-48a6-a473-0fc7690a1788.png)

### Housekeeping

- Package rename (`com.khartec` -> `org.finos`)
- More integration / unit tests
- Javascript Library refresh(Java lib refresh will be part of 1.40)

**Comment by balbirthomas** [comment]
Waltzing into 2022.

**Comment by davidwatkins73** [comment]
Hi!

**Comment by ljubon** [comment]
Hello :)

**Comment by agitana** [comment]
hi! Aitana Myohl from FINOS

**Comment by waterfall49** [comment]
Hi! Cathy from RBC Capital Market.

**Comment by JWoodland-Scott** [comment]
Hi :)

**Comment by mcleo-d** [comment]
Noted from Russell Green over Webex chat ...

> Would it be worth getting a forum prioritisation of new features (including the APIs discussed) so people that are in interested in contributing can understand what where they will make the biggest impact. There must be common features/problems that we are experiencing.

**Comment by Russell-G** [comment]
Hi from Russell

**Comment by rhyddian** [comment]
Hey 👍

**Comment by pedroleaoc** [comment]
Is there a quick and easy "getting started with Waltz" tutorial that one can run using docker-compose locally and would take less than 20 minutes for a newbie to run?

**Comment by mcleo-d** [comment]
## Meeting Minutes 

- Run through of release `v1.39` as documented in the following GitHub comment ... 
  - https://github.com/finos/waltz/issues/5813#issuecomment-1012168674
- [ ] Create a `label` for community issues raised to categorise the ideas and requests coming from the wider FINOS community.
- It was suggested `first good issues` and `fixes` are tagged for community developers to get involved with. 
- It was suggested `use cases` are created to define how Waltz is being used so others can follow.
- A `public sandbox` was suggested with running examples of how Waltz is being applied
  - cc @pedroleaoc for #5852
  - It was suggested `Legend` could supply this through their `common data types` and `common APIs`.
  - Standardising on data and taxonomy would be useful, this can then be consumed by Waltz.
  - Waltz can then compare the data and taxonomy against internal banking applications.
    - [ ] List out the `highest priority entity types` and find out how they can be added to Legend.
  - This could be a use case for the public Waltz entity
-  Waltz `getting started videos` shared - https://waltz.finos.org/blog/index.html
- Run through of pull request #5801 💯 💯 💯
- Waltz community invited to raise issues against #5801 when found.
- Docker improvements and next steps - Helm Chart and Kubernetes integration.
- #5852 created and invitation sent to the Waltz project group. 
  - @ljubon it would be awesome if you can own #5801 and join the call with @davidwatkins73 as I'm sure the Docker contribution will be referenced.
- Will Waltz support data table `attribute level lineage`?
  - Waltz team does not have the capacity to do this as very complex.
  - Have discussed `solidatus` integration in the past.
    - https://www.solidatus.com/data-lineage/
  - Community contributions are welcome.
  - Legend does support attribute level lineage, so having a link between Waltz and Legend will be useful.
- [ ] Waltz conversation needed with the Deutsche Bank Legend team to understand priorities.
- FINOS All Community Call introduced to the group.
  - https://github.com/finos/community/issues/152
- GraphQL raised as a possible JS framework for Waltz APIs.
  - [ ] Create issue for the API technology discussion.

**Comment by ljubon** [comment]
Hi @davidwatkins73 , i would be glad to help! Also, I would consider helm charts too, as it's wider accepted imho.
For sure, I'll be happy to learn what's the options/benefits with Juju charts since so far I worked only with Helm

**Comment by davidwatkins73** [comment]
Hi @ljubon.  Looking forward to the session @2pm uk ( #5852 ).  Speak to you later.
