### ISSUE TITLE
Waltz Public Instance

### ISSUE THREAD

**Issue by pedroleaoc** [finos/waltz#5906]
### Description

The idea is to create a public instance of [Charmed Waltz](https://github.com/pedroleaoc/waltz-integration-juju) running on FINOS infrastructure. Similar to other FINOS public instances, members could explore the tool before devoting the time and resources to install it locally. The deployment would be made with Juju on Kubernetes following the work performed by [Charming Waltz Working Group](https://github.com/finos/waltz/issues?q=Waltz+Working+Group+%3A+Charming+Waltz+with+Juju). 

cc @mcleo-d @maoo 

### Resourcing

We would like to collaborate on this feature

**Comment by davidwatkins73** [comment]
I fully support this proposal.

**Comment by maoo** [comment]
Thanks for the issue @pedroleaoc and @davidwatkins73 for confirming your support!

My understanding is that you'd like to have a public Waltz instance like the FINOS Legend Shared instance on https://legend.finos.org/studio

From a technical standpoint, what we'd need to figure out is:
- [ ] Deployment mechanism is ready and tested (Juju charms for EKS + local, with microk8s)
- [ ] Authentication + authorization mechanism: will Waltz provide basic signup/signin ? Will access be restricted?
- [ ] Data management: will data be reset periodically, ie on weekly bases? Will there be data sandboxes for each user access?
- [ ] Monitoring and scaling
- [.] Sizing and cost estimate (based on AWS EKS)

I expect that costs will be manageable, but I'll have to submit the amount for review anyway.

Please let me know if I missed anything, and if you have any questions. Thanks!

**Comment by mcleo-d** [comment]
Link to sample data on @davidwatkins73 GitHub profile.

https://github.com/davidwatkins73/waltz-demo-docker/tree/master/waltz-sample-db

**Comment by mcleo-d** [comment]
> Deployment mechanism is ready and tested (Juju charms for EKS + local, with microk8s)

Targeting AWS EKS has been confirmed by the Waltz community.

cc @davidwatkins73

**Comment by mcleo-d** [comment]
Hey @pedroleaoc - There shouldn't be an issue. I'd suggest engaging with @maoo.

**Comment by maoo** [comment]
I already discussed this with Pedro ; in fact, his proposal comes from the request to keep costs under control, given that this is a demo instance. Based on its usage, we will later decide if/when/how to scale it.

@pedroleaoc - let's use Ec2 + microk8s as reference architecture for Waltz. Thanks!

**Comment by davidwatkins73** [comment]
**Q:** Data management: will data be reset periodically, ie on weekly bases? Will there be data sandboxes for each user access? Which part of data is preserved and which one is reset? @davidwatkins73 , @balbirthomas , @pedroleaoc

**A:** Data should be reset periodically (weekly?).  No sandboxes per user.  May need to update the client/server digest to force a reload after a database reset.  Initially we will look to use juju to perform the reset.

**Comment by davidwatkins73** [comment]
**Q:** Monitoring and Scaling
**A:** (Parital) Scalability should not be a problem, we run entire DB instance on a pair of 2gb (shared) tomcat services.

**Comment by mcleo-d** [comment]
> **A:** (Partial) Scalability should not be a problem, we run entire DB instance on a pair of 2gb (shared) tomcat services. 

@maoo - Regarding monitoring Tomcat, does AWS provide a notification service that could inform an email address if the services are interrupted or error?

**Comment by claudiubelu** [comment]
Apologies, it seems that something was up with the domain name that I own. I created a temporary domain name on another service and generated a new certificate. This is my current Waltz deployment on EKS + HTTPS enabled: https://test-waltz.ipq.co/

**Comment by balbirthomas** [comment]
Just keeping you updated @davidwatkins73 @mcleo-d . I am still exploring alternative solutions with multiple Juju/charm teams with regard to periodic resetting of Waltz public instance data. I will get back to you shortly on this, once the stars align :-) .

**Comment by mcleo-d** [comment]
Hi @kriscanonical, @balbirthomas, @pedroleaoc, @claudiubelu 👋🏻 

FINOS is planning an in-person Waltz meetup for **Wednesday 20th April** in London to help educate the FINOS community on Waltz and help drive contribution.

Having the Waltz AWS public instance done and available to browse would be an awesome feature to demo at the event. Do you think the following milestones are achievable to get this done ...

- **Wednesday 23rd March onwards** : Complete Waltz public instance with @maoo and @davidwatkins73.
  - @pedroleaoc - Can this also be coordinated with [Compliant Financial Infrastructure](https://github.com/finos/compliant-financial-infrastructure) if achievable - https://github.com/finos/compliant-financial-infrastructure/pull/195
  - @davidwatkins73 - Is white label data available for the public instance that can be reinstalled on a set cadence?
- **Thursday 14th April** : Demo completed Waltz public instance at next Waltz monthly project call.
- **Wednesday 20th April** : Demo completed Waltz public instance at FINOS Waltz meetup.

I'm happy to setup a project call to discuss if needed?

James.

**Comment by mcleo-d** [comment]
cc @maoo and @pedroleaoc, 

- [ ] SSL certificate on demo.waltz.finos.org
- [ ] David reviews the demo env, prepares a walkthrough for the meetup
- [ ] finos-waltz-bundle gets contributed to github.com/finos
- [ ] Merge all pending PRs on finos-waltz-bundle
- [ ] Validate Waltz charm (automated) release
- [ ] Review Waltz charm docs (maybe update waltz.finos.org)
- [ ] Automate deployment on demo.waltz.finos.org on every Waltz charm release

**Comment by robmoffat** [comment]
SSL Cert instructions here:  https://github.com/finos/waltz-juju-bundle/pull/1

**Comment by mcleo-d** [comment]
@TheJuanAndOnly99 and @robmoffat - Following the Waltz project meeting #6089, it's been determined SSL Certificate for the Waltz Public Instance can be applied by the FINOS infrastructure team.

https://github.com/finos/waltz/issues/5906#issuecomment-1097940997
> SSL certificate on demo.waltz.finos.org - @TheJuanAndOnly99 and @robmoffat

It would be great to schedule to move this forward. Thanks!

James.

**Comment by maoo** [comment]
@mcleo-d - unfortunately there's not much we can do on this, until we get a stable and working automation from @pedroleaoc and team.

**Comment by robmoffat** [comment]
Just these last two steps to figure out:

- [ ] SSL certificate on demo.waltz.finos.org - @TheJuanAndOnly99 and @robmoffat 
- [ ] Review Waltz charm docs (maybe update waltz.finos.org)

**Comment by maoo** [comment]
Docs can be found on:

**Comment by claudiubelu** [comment]
Hello,

As you can see, the SSL certificate has been added to [demo.waltz.finos.org](https://demo.waltz.finos.org). The Waltz Public Instance is currently running with the PostgreSQL sample database which can be found here: https://github.com/finos/waltz/blob/master/waltz-sample-data/database/pg/dump.sql.tar.gz . The sample database is being reset every 2 hours, as we've decided some time ago (any changes to the data will be reset).

Waltz can be deployed by using the ``finos-waltz-k8s`` charm (https://github.com/finos/waltz-integration-juju and https://charmhub.io/finos-waltz-k8s). It can be configured with an external PostgreSQL database, or it can be configured to run with a ``postgresql-k8s`` charm, which will create and maintain the PostgreSQL database instead (including credentials created for any related charm).

Typically, multiple charms can be deploy a lot easier through a bundle, and we do have a Waltz bundle, which can be found here: https://github.com/finos/waltz-juju-bundle and https://charmhub.io/finos-waltz-bundle?channel=1.39/edge . There is also a Waltz Public bundle, which will also contain the PostgreSQL sample database as well (can be found here: https://github.com/finos/waltz-juju-bundle/tree/public and https://charmhub.io/finos-waltz-bundle?channel=public/edge).

As for the documentation, there are a few noteworthy ones:

- The ``finos-waltz-k8s`` [readme file](https://github.com/finos/waltz-integration-juju). This readme also contains information regarding the charm and bundle release automation process, which might be interesting for you as well.
- The ``finos-waltz-bundle`` [readme file](https://github.com/finos/waltz-juju-bundle). This readme also contains information about the charms contained in the regular bundle and in the public data bundle.
- [Local deployment guide](https://github.com/finos/waltz-juju-bundle/blob/main/docs/guides/LocalDeployment.md), how to deploy Waltz in your local environment. Other guides could be added as well. For example, for Legend we also have an EKS deployment guide. For example, I think it would be useful to have a guide for a public cloud and how to configure a hostname for a Waltz deployment, and how to generate SSL certificates for it.
- ``finos-waltz-k8s`` charm developer guide: https://github.com/finos/waltz-integration-juju/blob/main/docs/DeveloperGuide.md . This is a useful document for anyone who would want to contribute to the finos-waltz-k8s charm, including how to test local changes, including linting, unit testing, integration testing (in which we're deploying a one node Kubernetes cluster in which we deploy all the necessary charms and make sure that Waltz is reachable).

We have quite a few github actions running on these projects, including [lint, unit test, and integration tests](https://github.com/finos/waltz-integration-juju/blob/main/.github/workflows/ci.yaml) that are running on every Pull Request. There are a few actions that are using various tokens which have a limited TTL, which would have to be refreshed in the future. They are also documented here:

- [waltz-integration-juju Charm publishing action](https://github.com/finos/waltz-integration-juju/blob/main/.github/workflows/publish.yaml): This action runs whenever a PR merges. It builds a new charm and pushes it to charmhub.io on the edge channel. Documentation regarding the tokens: https://github.com/finos/waltz-integration-juju/blob/main/docs/CharmPublishing.md
- [waltz-juju-bundle](https://github.com/finos/waltz-juju-bundle/blob/main/.github/workflows/publish_images.yaml): This actions runs daily or on demand, and will create new ``finos-waltz-k8s`` and ``finos-waltz-bundle`` releases on charmhub.io based on the Waltz releases. For more information regarding the release process, see the [Readme](https://github.com/finos/waltz-integration-juju). Documentation regarding the tokens can be found here: https://github.com/finos/waltz-juju-bundle/blob/main/docs/CharmhubPublishing.md

Finally, the Waltz Public Instance is updated daily to the latest revisions due to [this action](https://github.com/finos/waltz-integration-juju/blob/main/.github/workflows/refresh_deployment.yaml). For more information about how it was set up, see here: https://github.com/finos/waltz-integration-juju/blob/main/docs/periodic_job.md

If I missed anything, please let me know. :)

**Comment by maoo** [comment]
Love the recap @claudiubelu , thanks so much! I wonder if we could copy/paste this content somewhere? I see that docs are located in many places, so it may be interesting to understand "what is where" and if there are chances to consolidate them in some way, eager to hear your feedback.

- https://github.com/finos/waltz/blob/master/README.md - may be the best place to add the recap above
- https://github.com/finos/waltz-integration-juju/blob/main/README.md - the Waltz charm itself
- https://github.com/finos/waltz-integration-juju/tree/main/docs - how to manage the charm
- https://github.com/finos/waltz-juju-bundle/blob/main/README.md - the Waltz Juju bundle
- https://github.com/finos/waltz-juju-bundle/tree/main/docs - how to manage the bundle

Finally - slightly connected - there's an open issue that is currently preventing us to do automatic releases of the Juju bundle, see https://github.com/finos/waltz-juju-bundle/issues/15 . @pedroleaoc is trying to reproduce and follow up internally.
