### ISSUE TITLE
Involvement and Involvement_kind

### ISSUE THREAD

**Issue by shaunparsloe** [finos/waltz#6003]
### Description

I have loaded our organisational units into the OrgUnits table and then the Employees into the People table.  For each person I have populated their orgunitID.
Now in Waltz I can view the person under /profile/view/<personName> and I can see their managers and direct reports.
Also under /person/id/<personId> I can see their data including Org Unit. 
When I click on the Org Unit it takes me to /org-units/<orgUnitId> and I can see all the applications for that OrgUnit.

However on that org-units page the People section is blank and it states `No people have been associated.`

I guess that I need to populate the Involvement table with all people involved in that Org Unit, but I am unsure if this is correct as this feels a duplicate of having the OrgUnit populated in the People table.
Initially I was going to populate the Involvement_kind table with all the Job Titles here, but we have literally hundreds of Job titles (e.g. Algo Safety Senior Analyst,  Application Architect, Associate General Counsel etc.) and so I think that I'm possibly going down the wrong route.

What is the purpose of the Involvement table when it comes to Org Units?  Is it meant to show some different kind of relationship between team and the members/managers of the team?  What do you use the People section for?

**Comment by davidwatkins73** [comment]
We don't show the people linked to OU's via their person record as this gets unwieldy (10's of thousands of people as we ascend the tree).  Instead we use the `involvement` table to call out key individuals (Department Heads, Domain Architects etc).

For the job titles we have that on the `person` record, but the `involvement table` is more 'role' oriented rather than title oriented.  Though we do have around 60 `involvement_kind`s defined (e.g. Developer, Project Manager, Application Owner).

We could certainly look to add the complete list of associated people to the OU person section, but would need to ensure we don't negatively impact performance (perhaps lazy loading or just displaying a summary data once a limit has been hit).  Feel free to create a feature request if this is something you'd like to add to our backlog :)

Hope this helps. 

(BTW if you are in London next week we are doing an [in-person event with FINOS on the 20th April](https://zoom.us/webinar/register/7616482278370/WN__Fug8-UKQM2YgdcqRrQcKg) )
