### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by janousekdusan** [finos/waltz#6146]
Dear All

I would like to ask you if you can help me with my problem which was appeared after upgrade of operation system.
I want to install last version of Waltz. I already synchronized local version GIT repository and continued by install steps which are presented on GIT WIKI.

Here is a command for building.
mvn clean compile -X -P waltz-mariadb,dev-maria

Log is included here.
[report.txt](https://github.com/finos/waltz/files/9175561/report.txt)

Error:
Execution default of goal org.liquibase:liquibase-maven-plugin:3.10.3:update failed: Index 1 out of bounds for length 1
Probably the problem could be with the tool liquibase.  If I try to use the new version of liquibase 4.13, I get another sort of errors.

Is it possible to go step over and build database by importing of DB schema?

Configuration of linux server
Linux
Ubuntu 18.04
RAM 6GB
64 GB Disk space

If you need more information, please let me know.

Best regards

Dusan Janousek
email: janousek@djsystems.cz

**Comment by davidwatkins73** [comment]
Hi @janousekdusan ,

I see you are trying to build on Maria.  We haven't given it much attention for the last year or so, we dropped it from the official list of supported databases due to lack of interest).  

If it's important for you to get it working with Maria (as opposed to Postgres) we can take a look to see which liquibase changes are causing the issue and see if it's an easy fix.

Thanks for reaching out

/dw
